### ISSUE TITLE
TASK [alphacorvus.ansible_tor_bridge : Register result]    fails

### ISSUE THREAD

**Issue by toralf** [NewNewYorkBridges/ansible-tor-bridge#10]
Running https://github.com/toralf/tor-relays/blob/main/cert.yml yields to (snip'ed sensitive data):
```
TASK [alphacorvus.ansible_tor_bridge : Register cert] ***************************************************************************************************************************************
task path: /home/tfoerste/.ansible/roles/alphacorvus.ansible_tor_bridge/tasks/bridge_line.yml:21
ok: [<snip>] => {"ansible_facts": {"cert": ["<snip>"]}, "changed": false}

TASK [alphacorvus.ansible_tor_bridge : Register result] *************************************************************************************************************************************
task path: /home/tfoerste/.ansible/roles/alphacorvus.ansible_tor_bridge/tasks/bridge_line.yml:27
fatal: [zwiebeltoralf5]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/home/tfoerste/.ansible/roles/alphacorvus.ansible_tor_bridge/tasks/bridge_line.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Register result\n  ^ here\n"}
```
at a recent Debian.

**Comment by lilianbaz** [comment]
The task `bridge_line.yml` is an optional task that create a temporary file on the ansible node with the information of your bridges. It use the public IP in the var `public_ip`.
You can set it directly on the Ansible host file for each bridge. If the public IP is directly attached to a network interface (for example, ens3) you can to this: `public_ip={{ ansible_ens3.ipv4.address }}`.

It's not well documented... we just write it at the end of the README! Maybe we need to update the host file example for better understanding

**Comment by toralf** [comment]
> The task `bridge_line.yml` is an optional task that create a temporary file on the ansible node with the information of your bridges. It use the public IP in the var `public_ip`. You can set it directly on the Ansible host file for each bridge. If the public IP is directly attached to a network interface (for example, ens3) you can to this: `public_ip={{ ansible_ens3.ipv4.address }}`.
> 
> It's not well documented... we just write it at the end of the README! Maybe we need to update the host file example for better understanding

Hhm, I did it (otherwise I would get "undefined public_ip") - the issue still exists :-/

**Comment by toralf** [comment]
A debug unveils that fingerprint[0] is wrong, it shall be just fingerprint IMO.

**Comment by toralf** [comment]
I tis the {{ fingerprint }} variable which is empty - but the fingerprint file has content.

**Comment by lilianbaz** [comment]
Erf, thanks for pointing this!
Updated, according to the man _Nicknames must be between 1 and 19 characters inclusive, and must contain only the characters [a-zA-Z0-9]._.
