### ISSUE TITLE
overwrite the torrc Nickname 

### ISSUE THREAD

**Issue by toralf** [NewNewYorkBridges/ansible-tor-bridge#11]
Currently the torrc Nickname is hard coded to the hostname. 

Whilst the user can overwrite it, eg by https://github.com/toralf/tor-relays/blob/main/hosts.example.yml#L9 I do wonder if there's a better solution than having two Nickname lines in torrc ?

**Comment by toralf** [comment]
BTW does additionnal has 1 "n" too much ?

**Comment by lilianbaz** [comment]
Hardcoded value for `nickname`, `extorport` and `obfs4_ip` were replaced by vars and declared in `default/main.yml`, so you can now override this values by declaring them in host file for example.
