### ISSUE TITLE
Error installing tor packages on Ubuntu 20.04

### ISSUE THREAD

**Issue by pjsier** [NewNewYorkBridges/ansible-tor-bridge#3]
When running this without any tags specified on a new DigitalOcean server running Ubuntu 20.04 I run into the following error when installing tor packages:

```
The following packages have unmet dependencies:
 tor : Depends: runit-helper (>= 2.10.0~) but 2.8.14ubuntu2 is to be installed
       Recommends: tor-geoipdb but it is not going to be installed
       Recommends: torsocks but it is not going to be installed
```

Is 20.04 not supported or is there another issue with the packages to install?

**Comment by lilianbaz** [comment]
Hi pjsier,
The bullseye distribution was hardcoded on the `tor.list` file...
I modify this file into a template and add the `ansible_distribution_release` var so it should work now on Ubuntu.
