### ISSUE TITLE
please support private bridges  and user defined nickname

### ISSUE THREAD

**Issue by toralf** [NewNewYorkBridges/ansible-tor-bridge#6]
As described in https://gitlab.torproject.org/tpo/core/tor/-/issues/40430 these 2 torrc values are needed:

```
PublishServerDescriptor 1
BridgeDistribution none
```

**Comment by toralf** [comment]
Thinking more about this it seems that there are much more config values too - maybe just add something like {{ additional_config }} to the appropriate *.j2 file and let the user configure that string (with \n in it) ?

**Comment by lilianbaz** [comment]
That's a good idea: I just pushed a change with the new var `additionnal_torrc_config` and set `PublishServerDescriptor bridge` as an example in the `default/main.yml`. Do you think it fits your need?

I'm not sure what are the best default options at the moment, we'll probably change that later.

**Comment by toralf** [comment]
cool - works (maybe 2 newlines after each line are 1 too much but otherwise works fine).
Thx!
