### ISSUE TITLE
high port usage forbidden and needs to be activated

### ISSUE THREAD

**Issue by toralf** [NewNewYorkBridges/ansible-tor-bridge#8]
At a fresh new Hetzner VPS I do get
```
Mar 05 17:11:27.000 [warn] Server managed proxy encountered a method error. (obfs4 listen tcp 0.0.0.0:443: bind: permission denied)
Mar 05 17:11:27.000 [warn] Managed proxy at '/usr/bin/obfs4proxy' failed the configuration protocol and will be destroyed.
```

**Comment by toralf** [comment]
What helped by https://www.mail-archive.com/tor-relays@lists.torproject.org/msg16552.html
```
https://gitlab.torproject.org/tpo/core/tor/-/issues/18356 tells 
```

**Comment by lilianbaz** [comment]
Hi toralf,
I just made some modifications to run the `setcap` and to override systemd services.
It should work as expected when the var obfs4port is under 1024 (for Debian/Ubuntu only, I'm searching how to do the same thing on FreeBSD).

**Comment by toralf** [comment]
ok, works here now under Debian
